### ISSUE TITLE
I can't find the file name in vocabulary_refresh.

### ISSUE THREAD

**Issue by Kisooofficial** [OHDSI/MIMIC#23]
Hello, I am a university student in Korea who is doing a process to convert MIMIC4 to OCOP CDM. 
I downloaded whole files in this github. Now, the files are in 
C:\Users\MyName\MIMIC-master\vocabulary_refresh
But, I can't find the file corresponding to vocabulary_2020_09_11. Have you ever changed this file name? I want to find local_athena_csv_path.

**Comment by mik-ohdsi** [comment]
Hi @Kisooofficial - we do not keep the vocabulary files in this github (would become pretty large). You are supposed to download your own set of vocabularies from Athena, then add the custom local vocabularies (2bn ids). Find attached information about the current vocabulary table in the latest ETL conversion for your reference.
[vocabulary_table.csv](https://github.com/OHDSI/MIMIC/files/11123408/vocabulary_table.csv)

**Comment by Kisooofficial** [comment]
Thank you for comment. I've already resolved problems. Thank you.
